// finpro-mobile-expo/src/app/(dashboard)/progress.tsx
import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, ActivityIndicator, RefreshControl } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { useRouter } from 'expo-router';
import { useColorScheme } from 'nativewind';
import * as SecureStore from 'expo-secure-store';
import { dashboardApi } from '../../services/api';

export default function ProgressScreen() {
  const { colorScheme } = useColorScheme();
  const router = useRouter();
  const [profile, setProfile] = useState<any>(null);
  const [progressData, setProgressData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const loadData = async () => {
    try {
      const stored = await SecureStore.getItemAsync('srl_profile');
      if (stored) {
        try {
          setProfile(JSON.parse(stored));
        } catch (e) {}
      }
      
      const res = await dashboardApi.getProgress();
      if (res.data) {
        setProgressData(res.data);
        if (res.data.latest_result?.CategoryResult) {
          setProfile(JSON.parse(res.data.latest_result.CategoryResult));
        }
      }
    } catch (err) {
      console.log('Error loading progress:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const onRefresh = async () => {
    setRefreshing(true);
    await loadData();
    setRefreshing(false);
  };

  if (isLoading) {
    return (
      <View className="flex-1 bg-surface-warm dark:bg-dark-bg items-center justify-center">
        <ActivityIndicator size="large" color="#F97316" />
      </View>
    );
  }

  const dimensionDelta = progressData?.dimension_delta;
  const dimensions = [
    { key: 'planning', label: 'Planning' },
    { key: 'time_management', label: 'Time Management' },
    { key: 'cognitive', label: 'Cognitive Strategy' },
    { key: 'reflection', label: 'Reflection' }
  ];

  let canRetake = true;
  let daysUntilRetake = 0;
  if (progressData?.latest_result?.CreatedAt) {
    const lastDate = new Date(progressData.latest_result.CreatedAt);
    const now = new Date();
    const diffTime = now.getTime() - lastDate.getTime();
    const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
    
    if (diffDays < 14) {
      canRetake = false; 
      daysUntilRetake = 14 - diffDays;
    }
  }

  return (
    <View className="flex-1 bg-surface-warm dark:bg-dark-bg">
      <StatusBar style={colorScheme === "dark" ? "light" : "dark"} />
      <ScrollView 
        className="flex-1" 
        contentContainerStyle={{ paddingBottom: 32 }}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={['#F97316']} tintColor="#F97316" />
        }
      >
        
        {/* Header */}
        <View className="px-6 pt-16 pb-6 border-b border-navy-100 dark:border-dark-border">
          <Text className="text-3xl font-black text-navy-900 dark:text-text-primary mb-2">Progress</Text>
          <Text className="text-navy-500 dark:text-text-muted font-medium text-xs">
            Track your learning development over time.
          </Text>
        </View>

        {/* Stats Row */}
        <ScrollView horizontal showsHorizontalScrollIndicator={false} className="px-6 mt-6 mb-6 pb-2" contentContainerStyle={{ gap: 12 }}>
          <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border p-4 rounded-3xl w-40 shadow-sm">
            <Text className="text-navy-500 dark:text-text-muted text-[9px] font-black uppercase tracking-widest mb-1">Current Profile</Text>
            <Text className="text-navy-900 dark:text-text-primary text-lg font-black mt-1" numberOfLines={1}>{profile?.profile_title || 'Learner'}</Text>
          </View>
          <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border p-4 rounded-3xl w-40 shadow-sm">
            <Text className="text-navy-500 dark:text-text-muted text-[9px] font-black uppercase tracking-widest mb-1">Consistency</Text>
            <Text className="text-brand-500 text-3xl font-black">{profile?.consistency_score || 0}%</Text>
            <Text className="text-navy-500 dark:text-text-muted text-[10px] mt-1">active days / week</Text>
          </View>
          <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border p-4 rounded-3xl w-40 shadow-sm">
            <Text className="text-navy-500 dark:text-text-muted text-[9px] font-black uppercase tracking-widest mb-1">Deep Work</Text>
            <Text className="text-emerald-500 dark:text-emerald-400 text-3xl font-black">{profile?.deep_work_capacity || 0}%</Text>
            <Text className="text-navy-500 dark:text-text-muted text-[10px] mt-1">capacity</Text>
          </View>
          <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border p-4 rounded-3xl w-40 shadow-sm">
            <Text className="text-navy-500 dark:text-text-muted text-[9px] font-black uppercase tracking-widest mb-1">Retention</Text>
            <Text className="text-violet-500 dark:text-violet-400 text-3xl font-black">{profile?.retention_score || 0}%</Text>
            <Text className="text-navy-500 dark:text-text-muted text-[10px] mt-1">knowledge retention</Text>
          </View>
        </ScrollView>

        {/* SRL Score Trend */}
        <View className="px-6 mb-6">
          <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border p-6 rounded-3xl shadow-sm">
            <Text className="text-navy-900 dark:text-text-primary text-base font-black mb-6">SRL Score Trend</Text>
            
            {progressData?.assessment_trend?.length > 0 ? (
              <View className="gap-3">
                {progressData.assessment_trend.map((entry: any) => {
                  const date = new Date(entry.CreatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
                  const scores = [entry.PlanningScore, entry.TimeManagementScore, entry.CognitiveScore, entry.ReflectionScore].filter(s => s != null);
                  const rawAvg = scores.length > 0 ? scores.reduce((a, b) => a + b, 0) / scores.length : 0;
                  const avg = Math.round((rawAvg / 25) * 100);
                  
                  return (
                    <View key={entry.ResultID} className="flex-row items-center gap-3">
                      <Text className="text-navy-500 dark:text-text-muted text-[10px] font-bold w-20">{date}</Text>
                      <View className="flex-1 h-2 bg-navy-50 dark:bg-dark-surface rounded-full overflow-hidden">
                        <View className="h-full bg-brand-500 rounded-full" style={{ width: `${avg}%` }} />
                      </View>
                      <Text className="text-navy-900 dark:text-text-primary text-[10px] font-black w-8 text-right">{avg}%</Text>
                    </View>
                  );
                })}
              </View>
            ) : (
              <View>
                <View className="flex-row items-center justify-between mb-2">
                  <Text className="text-navy-500 dark:text-text-muted text-[10px] font-bold">Latest Assessment</Text>
                  <Text className="text-navy-900 dark:text-text-primary text-xs font-black">{profile?.consistency_score || 85}%</Text>
                </View>
                <View className="h-2 bg-navy-50 dark:bg-dark-surface rounded-full overflow-hidden">
                  <View className="h-full bg-brand-500 rounded-full" style={{ width: `${profile?.consistency_score || 85}%` }} />
                </View>
              </View>
            )}
          </View>
        </View>

        {/* Dimension Analysis */}
        <View className="px-6 mb-6">
          <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border p-6 rounded-3xl shadow-sm">
            <Text className="text-navy-900 dark:text-text-primary text-base font-black mb-6">Dimension Analysis</Text>
            
            {!dimensionDelta ? (
              <View className="items-center py-4">
                <Text className="text-navy-500 dark:text-text-muted text-xs text-center font-bold">
                  Take another assessment later to unlock comparative dimension analysis.
                </Text>
              </View>
            ) : (
              <View className="flex-row flex-wrap justify-between gap-y-4">
                {dimensions.map(dim => {
                  const delta = dimensionDelta[dim.key] || 0;
                  const isPositive = delta > 0;
                  const isNegative = delta < 0;
                  
                  return (
                    <View key={dim.key} className="bg-surface-warm dark:bg-dark-bg border border-navy-100 dark:border-dark-border p-4 rounded-2xl w-[48%]">
                      <Text className="text-navy-500 dark:text-text-muted text-[9px] font-black uppercase tracking-widest mb-2">{dim.label}</Text>
                      <View className="flex-row items-center gap-2">
                        <Text className={`text-2xl font-black ${isPositive ? 'text-emerald-500 dark:text-emerald-400' : isNegative ? 'text-rose-500 dark:text-rose-400' : 'text-navy-500 dark:text-text-muted'}`}>
                          {isPositive ? '+' : ''}{delta}
                        </Text>
                        {isPositive && <Text className="text-emerald-500 dark:text-emerald-400 font-bold text-lg leading-none mt-1">↑</Text>}
                        {isNegative && <Text className="text-rose-500 dark:text-rose-400 font-bold text-lg leading-none mt-1">↓</Text>}
                        {!isPositive && !isNegative && <Text className="text-navy-500 dark:text-text-muted font-bold">—</Text>}
                      </View>
                    </View>
                  );
                })}
              </View>
            )}
          </View>
        </View>

        {/* CTA Buttons */}
        <View className="px-6">
          <TouchableOpacity 
            className={`${canRetake ? 'bg-brand-500' : 'bg-brand-300 dark:bg-brand-500/50'} px-6 py-4 rounded-2xl w-full items-center shadow-sm flex-row justify-center gap-2`}
            onPress={() => {
              if (canRetake) {
                router.push('/(auth)/survey');
              } else {
                alert(`You can retake the assessment in ${daysUntilRetake} days.`);
              }
            }}
            activeOpacity={canRetake ? 0.7 : 1}
          >
            <Text className="text-white font-black text-sm">
              {canRetake ? '⟳ Retake Assessment' : `⟳ Available in ${daysUntilRetake} days`}
            </Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </View>
  );
}

// finpro-fe-VILT/resources/js/Pages/Dashboard/Progress.vue
<template>
  <DashboardLayout 
    :showBuddy="true"
    buddyContextTitle="Progress Insight" 
    :buddyContextMessage="insightMessage"
  >
    <!-- Header -->
    <div class="mb-10">
      <h1 class="text-3xl font-black text-navy-900 dark:text-text-primary mb-2">Progress</h1>
      <p class="text-navy-500 dark:text-text-muted font-medium">Track your learning development over time.</p>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="space-y-6">
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div v-for="i in 4" :key="i" class="h-28 bg-[#E8EDF2] dark:bg-dark-border rounded-[28px] animate-pulse"></div>
      </div>
      <div class="h-64 bg-[#E8EDF2] dark:bg-dark-border rounded-[28px] animate-pulse"></div>
    </div>

    <template v-else>
      <!-- Metric Cards -->
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-10">
        <!-- Current Profile -->
        <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
          <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Current Profile</p>
          <p v-if="progress.latest_result" class="text-lg font-black text-navy-900 dark:text-text-primary truncate">{{ profileTitle }}</p>
          <p v-else class="text-sm font-bold text-navy-400 dark:text-text-faint">No profile yet</p>
          <a v-if="!progress.latest_result" :href="route('onboarding.sanctuary')" class="text-xs text-brand-500 font-bold mt-2 inline-block hover:underline">Take Assessment →</a>
        </div>
        <!-- Consistency -->
        <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
          <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Consistency</p>
          <p class="text-3xl font-black text-brand-500">{{ consistencyScore }}%</p>
          <p class="text-xs font-bold text-navy-400 dark:text-text-faint mt-1">Active Days / Week</p>
        </div>
        <!-- Deep Work -->
        <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
          <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Deep Work</p>
          <p class="text-3xl font-black text-emerald-500">{{ deepWorkScore }}%</p>
          <p class="text-xs font-bold text-navy-400 dark:text-text-faint mt-1">Capacity</p>
        </div>
        <!-- Retention -->
        <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
          <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Retention</p>
          <p class="text-3xl font-black text-purple-500">{{ retentionScore }}%</p>
          <p class="text-xs font-bold text-navy-400 dark:text-text-faint mt-1">Knowledge Retained</p>
        </div>
      </div>

      <!-- SRL Score Trend -->
      <div class="bg-white dark:bg-dark-panel p-8 rounded-[32px] border border-[#D9E2EC] dark:border-dark-border shadow-sm mb-10">
        <h3 class="text-lg font-black text-navy-900 dark:text-text-primary mb-6">SRL Score Trend</h3>
        <div v-if="trendData.length === 0" class="text-center py-10">
          <p class="text-navy-400 dark:text-text-muted font-bold">No assessment data yet. Take your first assessment to see trends.</p>
        </div>
        <div v-else class="space-y-3">
          <div v-for="entry in trendData" :key="entry.ResultID" class="flex items-center gap-4">
            <span class="text-xs font-bold text-navy-400 dark:text-text-faint w-24 flex-shrink-0">{{ formatDate(entry.CreatedAt) }}</span>
            <div class="flex-1 flex items-center gap-2">
              <div class="flex-1 h-3 bg-[#FAFAF9] dark:bg-dark-surface rounded-full overflow-hidden">
                <div class="h-full bg-gradient-to-r from-brand-500 to-indigo-400 rounded-full transition-all duration-500" :style="{ width: `${avgScore(entry)}%` }"></div>
              </div>
              <span class="text-sm font-black text-navy-900 dark:text-text-primary w-12 text-right">{{ avgScore(entry) }}%</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Dimension Analysis -->
      <div class="bg-white dark:bg-dark-panel p-8 rounded-[32px] border border-[#D9E2EC] dark:border-dark-border shadow-sm mb-10">
        <h3 class="text-lg font-black text-navy-900 dark:text-text-primary mb-6">Dimension Analysis</h3>
        <div v-if="!progress.dimension_delta" class="text-center py-10">
          <p class="text-navy-400 dark:text-text-muted font-bold">Take another assessment later to unlock comparative dimension analysis.</p>
        </div>
        <div v-else class="grid grid-cols-2 lg:grid-cols-4 gap-4">
          <div v-for="(dim, key) in dimensionLabels" :key="key" class="bg-[#FAFAF9] dark:bg-dark-surface p-5 rounded-2xl border border-[#D9E2EC] dark:border-dark-border">
            <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">{{ dim }}</p>
            <div class="flex items-center gap-2">
              <span class="text-2xl font-black" :class="deltaColor(progress.dimension_delta[key])">
                {{ progress.dimension_delta[key] > 0 ? '+' : '' }}{{ progress.dimension_delta[key] || 0 }}
              </span>
              <svg v-if="progress.dimension_delta[key] > 0" class="w-4 h-4 text-emerald-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 15l7-7 7 7"/></svg>
              <svg v-else-if="progress.dimension_delta[key] < 0" class="w-4 h-4 text-rose-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M19 9l-7 7-7-7"/></svg>
              <span v-else class="text-xs font-bold text-navy-400 dark:text-text-faint">—</span>
            </div>
          </div>
        </div>
      </div>

      <!-- CTA Buttons -->
      <div class="flex flex-wrap gap-4">
        <a v-if="canRetake" :href="route('onboarding.sanctuary') + '?retake=true'" class="btn-primary text-white px-6 py-3 rounded-2xl font-bold transition-all active:scale-95 flex items-center gap-2 shadow-glow">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
          Retake Assessment
        </a>
        <div v-else class="bg-[#E8EDF2] dark:bg-dark-surface text-navy-400 dark:text-text-muted px-6 py-3 rounded-2xl font-bold flex items-center gap-2 cursor-not-allowed">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
          Next assessment in: {{ timeUntilNextAssessment }}
        </div>
      </div>
    </template>

  </DashboardLayout>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { usePage } from '@inertiajs/vue3'
import DashboardLayout from '@/Layouts/DashboardLayout.vue'
import { progressApi, setWorkspaceToken } from '@/services/workspaceApi'

const page = usePage()
const isLoading = ref(true)
const progress = ref({})

const dimensionLabels = {
  planning: 'Planning',
  time_management: 'Time Management',
  cognitive: 'Cognitive Strategy',
  reflection: 'Reflection'
}

const trendData = computed(() => progress.value.assessment_trend || [])

const profileData = computed(() => {
  const r = progress.value.latest_result
  if (!r) return null
  try {
    if (r.CategoryResult) {
      return JSON.parse(r.CategoryResult)
    }
  } catch {}
  return null
})

const profileTitle = computed(() => profileData.value?.profile_title || 'Learner')
const consistencyScore = computed(() => profileData.value?.consistency_score || 0)
const deepWorkScore = computed(() => profileData.value?.deep_work_capacity || 0)
const retentionScore = computed(() => profileData.value?.retention_score || 0)

const insightMessage = computed(() => {
  if (trendData.value.length < 2) return 'Take another assessment later to unlock comparison and dimension analysis.'
  return 'Great consistency! Keep refining your learning strategies to improve your SRL scores.'
})

const timeUntilNextAssessment = ref('')
let timerInterval = null

const canRetake = computed(() => {
  if (!progress.value.latest_result || !progress.value.latest_result.CreatedAt) return true;
  const lastDate = new Date(progress.value.latest_result.CreatedAt);
  const now = new Date();
  const diffTime = now.getTime() - lastDate.getTime();
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
  return diffDays >= 14;
})

function updateCountdown() {
  if (!progress.value.latest_result || !progress.value.latest_result.CreatedAt) return;
  const lastDate = new Date(progress.value.latest_result.CreatedAt);
  const nextDate = new Date(lastDate.getTime() + 14 * 24 * 60 * 60 * 1000);
  const now = new Date();
  const diff = nextDate - now;
  
  if (diff <= 0) {
    timeUntilNextAssessment.value = '';
    return;
  }
  
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));
  const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
  
  timeUntilNextAssessment.value = `${days}d ${hours}h ${minutes}m`;
}

onMounted(async () => {
  setWorkspaceToken(page.props.go_token)
  try {
    progress.value = await progressApi.getProgress()
    updateCountdown()
    timerInterval = setInterval(updateCountdown, 60000)
  } catch (err) {
    console.error('Failed to fetch progress', err)
  } finally {
    isLoading.value = false
  }
})

onUnmounted(() => {
  if (timerInterval) clearInterval(timerInterval)
})

function avgScore(entry) {
  const scores = [entry.PlanningScore, entry.TimeManagementScore, entry.CognitiveScore, entry.ReflectionScore].filter(s => s != null)
  if (scores.length === 0) return 0
  const avg = scores.reduce((a, b) => a + b, 0) / scores.length
  return Math.round(avg / 25 * 100) // Max score is 25 per dimension
}

function formatDate(dateStr) {
  if (!dateStr) return ''
  return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function deltaColor(val) {
  if (val > 0) return 'text-emerald-500'
  if (val < 0) return 'text-rose-500'
  return 'text-navy-400 dark:text-text-faint'
}
</script>
