// finpro-fe-VILT/resources/js/Pages/Dashboard/WeeklyTargets.vue
<template>
  <DashboardLayout 
    :showBuddy="true"
    buddyContextTitle="Target Insight" 
    :buddyContextMessage="insightMessage"
  >
    <!-- Header -->
    <div class="mb-10 flex flex-col md:flex-row md:items-end justify-between gap-6">
      <div>
        <h1 class="text-3xl font-black text-navy-900 dark:text-text-primary mb-2">Weekly Targets</h1>
        <p class="text-navy-500 dark:text-text-muted font-medium">Set measurable goals and track completion.</p>
      </div>
      <button @click="openTargetModal()" class="bg-gradient-to-r from-brand-500 to-brand-400 hover:from-brand-400 hover:to-brand-500 text-white px-6 py-3 rounded-2xl font-bold shadow-glow transition-all active:scale-95 whitespace-nowrap flex items-center gap-2">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 4v16m8-8H4"/></svg>
        Add Weekly Target
      </button>
    </div>

    <!-- Summary Cards -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-10">
      <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
        <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Total Targets</p>
        <p class="text-3xl font-black text-navy-900 dark:text-text-primary">{{ summary.total_targets || 0 }}</p>
      </div>
      <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
        <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Completed</p>
        <p class="text-3xl font-black text-emerald-500">{{ summary.completed_targets || 0 }}</p>
      </div>
      <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
        <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Completion Rate</p>
        <p class="text-3xl font-black text-brand-500">{{ Math.round(summary.completion_rate || 0) }}%</p>
      </div>
      <div class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm">
        <p class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Primary Focus</p>
        <p class="text-lg font-black text-navy-900 dark:text-text-primary truncate">{{ summary.primary_focus || 'No focus yet' }}</p>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="space-y-4">
      <div v-for="i in 3" :key="i" class="h-32 bg-[#E8EDF2] dark:bg-dark-border rounded-[28px] animate-pulse"></div>
    </div>

    <!-- Empty State -->
    <div v-else-if="targets.length === 0" class="bg-[#FAFAF9] dark:bg-dark-surface border-2 border-dashed border-[#D9E2EC] dark:border-dark-border p-12 rounded-[40px] text-center">
      <div class="flex justify-center mb-4 text-brand-500">
        <svg class="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
      </div>
      <p class="text-navy-500 dark:text-text-muted font-bold mb-2">No targets set yet.</p>
      <p class="text-navy-400 dark:text-text-faint text-sm">Create your first weekly target to start tracking your learning progress.</p>
      <button @click="openTargetModal()" class="mt-4 text-brand-500 font-bold hover:underline">+ Create Target</button>
    </div>

    <!-- Target Cards -->
    <div v-else class="space-y-6">
      <div v-for="target in targets" :key="target.id" class="bg-white dark:bg-dark-panel p-6 rounded-[28px] border border-[#D9E2EC] dark:border-dark-border shadow-sm hover:border-brand-200 dark:hover:border-brand-500/30 transition-all">
        <!-- Target Header -->
        <div class="flex items-start justify-between mb-4">
          <div class="flex-1">
            <div class="flex items-center gap-2 mb-2 flex-wrap">
              <span class="text-[10px] font-black uppercase tracking-widest px-2 py-1 rounded-md" :class="priorityClass(target.priority)">{{ target.priority }}</span>
              <span class="text-[10px] font-black bg-brand-50 dark:bg-brand-500/10 text-brand-500 uppercase tracking-widest px-2 py-1 rounded-md">{{ target.focus_dimension }}</span>
              <span class="text-[10px] font-black uppercase tracking-widest px-2 py-1 rounded-md" :class="statusBadge(target.status)">{{ target.status?.replace('_', ' ') }}</span>
            </div>
            <h4 class="text-lg font-black text-navy-900 dark:text-text-primary">{{ target.title }}</h4>
            <p v-if="target.description" class="text-sm font-medium text-navy-500 dark:text-text-muted mt-1">{{ target.description }}</p>
            <p v-if="target.due_date" class="text-xs font-bold text-navy-400 dark:text-text-faint mt-1">Due: {{ target.due_date }}</p>
          </div>
          <div class="flex items-center gap-2 ml-4">
            <button @click="openTargetModal(target)" class="w-9 h-9 rounded-xl bg-[#E8EDF2] dark:bg-white/10 text-navy-500 dark:text-navy-300 hover:bg-brand-500 hover:text-white dark:hover:bg-brand-500 dark:hover:text-white flex items-center justify-center transition-all shadow-sm border border-[#D9E2EC] dark:border-white/10 hover:border-brand-500 hover:shadow-md" title="Edit Target">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
            </button>
            <a :href="`/dashboard/planner?target_id=${target.id}`" class="w-9 h-9 rounded-xl bg-[#E8EDF2] dark:bg-white/10 text-navy-500 dark:text-navy-300 hover:bg-sky-500 hover:text-white dark:hover:bg-sky-500 dark:hover:text-white flex items-center justify-center transition-all shadow-sm border border-[#D9E2EC] dark:border-white/10 hover:border-sky-500 hover:shadow-md" title="Schedule Session">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
            </a>
            <a :href="`/dashboard/notes?target_id=${target.id}`" class="w-9 h-9 rounded-xl bg-[#E8EDF2] dark:bg-white/10 text-navy-500 dark:text-navy-300 hover:bg-purple-500 hover:text-white dark:hover:bg-purple-500 dark:hover:text-white flex items-center justify-center transition-all shadow-sm border border-[#D9E2EC] dark:border-white/10 hover:border-purple-500 hover:shadow-md" title="Add Reflection">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"/></svg>
            </a>
            <button @click="confirmDeleteTarget(target.id)" class="w-9 h-9 rounded-xl bg-[#E8EDF2] dark:bg-white/10 text-navy-500 dark:text-navy-300 hover:bg-rose-500 hover:text-white dark:hover:bg-rose-500 dark:hover:text-white flex items-center justify-center transition-all shadow-sm border border-[#D9E2EC] dark:border-white/10 hover:border-rose-500 hover:shadow-md" title="Delete Target">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
            </button>
          </div>
        </div>

        <!-- Progress Bar -->
        <div class="mb-4">
          <div class="flex items-center justify-between mb-1">
            <span class="text-[10px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest">Progress</span>
            <span class="text-sm font-black text-navy-900 dark:text-text-primary">{{ target.progress || 0 }}%</span>
          </div>
          <div class="w-full h-2 bg-[#E8EDF2] dark:bg-dark-border rounded-full overflow-hidden">
            <div class="h-full rounded-full transition-all duration-500" :class="target.progress >= 100 ? 'bg-emerald-500' : 'bg-brand-500'" :style="{ width: `${target.progress || 0}%` }"></div>
          </div>
        </div>

        <!-- Subtasks -->
        <div class="space-y-2">
          <div v-for="sub in target.subtasks" :key="sub.id" class="flex items-center gap-3 group">
            <button @click="toggleSubtask(target.id, sub.id)" class="w-5 h-5 rounded-md border-2 flex items-center justify-center flex-shrink-0 transition-all"
              :class="sub.is_completed ? 'bg-emerald-500 border-emerald-500' : 'border-[#D9E2EC] dark:border-dark-border hover:border-brand-500'">
              <svg v-if="sub.is_completed" class="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"/></svg>
            </button>
            <span class="text-sm font-bold flex-1" :class="sub.is_completed ? 'text-navy-400 dark:text-text-faint line-through' : 'text-navy-900 dark:text-text-primary'">{{ sub.title }}</span>
            <button @click="deleteSubtask(target.id, sub.id)" class="opacity-0 group-hover:opacity-100 w-6 h-6 rounded text-navy-400 dark:text-text-faint hover:text-rose-500 flex items-center justify-center transition-all">
              <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
            </button>
          </div>

          <!-- Add Subtask -->
          <div class="flex items-center gap-3 pt-2">
            <input v-model="newSubtask[target.id]" @keydown.enter="addSubtask(target.id)" placeholder="Add subtask..." class="flex-1 text-sm font-bold text-navy-900 dark:text-text-primary bg-transparent border-b border-dashed border-[#D9E2EC] dark:border-dark-border py-1 focus:border-brand-500 outline-none transition-colors placeholder:text-navy-300 dark:placeholder:text-text-faint">
            <button v-if="newSubtask[target.id]" @click="addSubtask(target.id)" class="text-brand-500 font-black text-xs hover:underline">Add</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Target Modal -->
    <Teleport to="body">
      <div v-if="showTargetModal" class="fixed inset-0 bg-[#0B1120]/60 dark:bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4" @click.self="showTargetModal = false">
        <div class="bg-white dark:bg-dark-panel rounded-[32px] p-8 w-full max-w-lg shadow-2xl max-h-[90vh] overflow-y-auto animate-slide-up border border-[#D9E2EC] dark:border-dark-border">
          <h2 class="text-xl font-black text-navy-900 dark:text-text-primary mb-6">{{ editingTarget ? 'Edit Target' : 'Add Weekly Target' }}</h2>
          <form @submit.prevent="saveTarget" class="space-y-5">
            <div>
              <label class="block text-[11px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Title *</label>
              <input v-model="targetForm.title" required class="w-full bg-[#FAFAF9] dark:bg-dark-surface border border-[#D9E2EC] dark:border-dark-border rounded-2xl py-3 px-5 text-sm font-bold text-navy-900 dark:text-text-primary focus:bg-white dark:focus:bg-dark-panel focus:border-brand-500 focus:ring-4 focus:ring-brand-500/10 outline-none transition-all" placeholder="e.g. Complete Chapter 5">
            </div>
            <div>
              <label class="block text-[11px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Description</label>
              <textarea v-model="targetForm.description" rows="2" class="w-full bg-[#FAFAF9] dark:bg-dark-surface border border-[#D9E2EC] dark:border-dark-border rounded-2xl py-3 px-5 text-sm font-bold text-navy-900 dark:text-text-primary focus:bg-white dark:focus:bg-dark-panel focus:border-brand-500 focus:ring-4 focus:ring-brand-500/10 outline-none resize-none transition-all"></textarea>
            </div>
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="block text-[11px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Focus Dimension</label>
                <select v-model="targetForm.focus_dimension" class="w-full bg-[#FAFAF9] dark:bg-dark-surface border border-[#D9E2EC] dark:border-dark-border rounded-2xl py-3 px-5 text-sm font-bold text-navy-900 dark:text-text-primary focus:bg-white dark:focus:bg-dark-panel focus:border-brand-500 outline-none appearance-none">
                  <option v-for="d in dimensions" :key="d" :value="d">{{ d }}</option>
                </select>
              </div>
              <div>
                <label class="block text-[11px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Priority</label>
                <select v-model="targetForm.priority" class="w-full bg-[#FAFAF9] dark:bg-dark-surface border border-[#D9E2EC] dark:border-dark-border rounded-2xl py-3 px-5 text-sm font-bold text-navy-900 dark:text-text-primary focus:bg-white dark:focus:bg-dark-panel focus:border-brand-500 outline-none appearance-none">
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                </select>
              </div>
            </div>
            <div>
              <label class="block text-[11px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Due Date</label>
              <input v-model="targetForm.due_date" type="date" class="w-full bg-[#FAFAF9] dark:bg-dark-surface border border-[#D9E2EC] dark:border-dark-border rounded-2xl py-3 px-5 text-sm font-bold text-navy-900 dark:text-text-primary focus:bg-white dark:focus:bg-dark-panel focus:border-brand-500 outline-none transition-all [color-scheme:light] dark:[color-scheme:dark]">
            </div>
            <!-- Initial Subtasks (create mode only) -->
            <div v-if="!editingTarget">
              <label class="block text-[11px] font-black text-navy-400 dark:text-text-faint uppercase tracking-widest mb-2">Initial Subtasks</label>
              <div v-for="(st, i) in targetForm.subtasks" :key="i" class="flex items-center gap-2 mb-2">
                <input v-model="st.title" class="flex-1 bg-[#FAFAF9] dark:bg-dark-surface border border-[#D9E2EC] dark:border-dark-border rounded-xl py-2 px-4 text-sm font-bold text-navy-900 dark:text-text-primary focus:border-brand-500 outline-none" :placeholder="`Subtask ${i + 1}`">
                <button type="button" @click="targetForm.subtasks.splice(i, 1)" class="text-navy-400 dark:text-text-faint hover:text-rose-500 font-bold">&times;</button>
              </div>
              <button type="button" @click="targetForm.subtasks.push({ title: '' })" class="text-sm text-brand-500 font-bold hover:underline">+ Add subtask</button>
            </div>
            <div class="flex gap-3 pt-4">
              <button type="button" @click="showTargetModal = false" class="flex-1 bg-[#E8EDF2] dark:bg-dark-surface text-navy-600 dark:text-text-primary py-3 rounded-2xl font-bold hover:bg-[#D9E2EC] dark:hover:bg-dark-border transition-colors">Cancel</button>
              <button type="submit" :disabled="isSaving" class="flex-1 btn-primary text-white py-3 rounded-2xl font-bold transition-all disabled:opacity-50 flex items-center justify-center">
                <svg v-if="isSaving" class="w-4 h-4 mr-2 animate-spin" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                {{ isSaving ? 'Saving...' : (editingTarget ? 'Update' : 'Create') }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </Teleport>

    <!-- Delete Target Modal -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="showDeleteModal" class="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div class="absolute inset-0 bg-[#0B1120]/60 dark:bg-black/60 backdrop-blur-sm" @click="showDeleteModal = false"></div>
          
          <div class="bg-white dark:bg-dark-panel border border-[#D9E2EC] dark:border-dark-border rounded-[32px] p-8 w-full max-w-md relative z-10 shadow-2xl animate-scale-up text-center">
            <div class="w-20 h-20 bg-rose-50 dark:bg-rose-500/10 text-rose-500 rounded-full flex items-center justify-center mx-auto mb-6 shadow-sm border border-rose-100 dark:border-rose-500/20">
              <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
            </div>
            
            <h3 class="text-2xl font-black text-navy-900 dark:text-text-primary mb-3">Delete Target</h3>
            <p class="text-navy-500 dark:text-text-muted text-sm font-medium mb-8 leading-relaxed">Are you sure you want to delete this target and all its subtasks? This action cannot be undone.</p>
            
            <div class="flex items-center gap-4">
              <button @click="showDeleteModal = false" class="flex-1 py-3.5 px-4 rounded-xl text-sm font-bold text-navy-500 dark:text-text-muted hover:text-navy-900 dark:hover:text-text-primary hover:bg-[#E8EDF2] dark:hover:bg-white/5 transition-all border border-transparent">
                Cancel
              </button>
              <button @click="executeDelete" class="flex-1 py-3.5 px-4 rounded-xl text-sm font-bold text-white bg-rose-500 hover:bg-rose-600 transition-all shadow-md shadow-rose-500/20 hover:shadow-rose-500/30">
                Yes, Delete
              </button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>

    <!-- Toast -->
    <Teleport to="body">
      <div v-if="toast" class="fixed bottom-6 right-6 z-50 bg-navy-900 dark:bg-dark-panel border border-navy-800 dark:border-dark-border shadow-2xl rounded-2xl p-4 flex items-center gap-3 animate-slide-up">
        <div class="w-8 h-8 rounded-lg flex items-center justify-center" :class="toast.type === 'error' ? 'bg-rose-500/20 text-rose-400' : 'bg-emerald-500/20 text-emerald-400'">
          <svg v-if="toast.type === 'error'" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
          <svg v-else class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"/></svg>
        </div>
        <span class="text-sm font-bold text-white">{{ toast.message }}</span>
      </div>
    </Teleport>

  </DashboardLayout>
</template>

<script setup>
import { ref, reactive, computed, onMounted, onUnmounted } from 'vue'
import { usePage } from '@inertiajs/vue3'
import DashboardLayout from '@/Layouts/DashboardLayout.vue'
import { targetsApi, setWorkspaceToken } from '@/services/workspaceApi'

const page = usePage()
const isLoading = ref(true)
const isSaving = ref(false)
const showTargetModal = ref(false)
const showDeleteModal = ref(false)
const targetToDelete = ref(null)
const editingTarget = ref(null)
const targets = ref([])
const summary = ref({})
const newSubtask = reactive({})
const toast = ref(null)

const dimensions = ['General', 'Planning', 'Time Management', 'Cognitive Strategy', 'Reflection']

const targetForm = ref({
  title: '', description: '', focus_dimension: 'General',
  priority: 'medium', due_date: '', subtasks: []
})

const insightMessage = computed(() => {
  if (targets.value.length === 0) return 'Create your first weekly target to make your learning goals measurable.'
  const totalSubs = targets.value.reduce((a, t) => a + (t.subtasks?.length || 0), 0)
  if (totalSubs < 3) return 'Break large goals into smaller subtasks to make progress easier to track.'
  return `You have ${targets.value.length} targets with ${totalSubs} subtasks. Keep completing them!`
})

onMounted(async () => {
  setWorkspaceToken(page.props.go_token)
  await fetchTargets()
  window.addEventListener('target-updated', fetchTargets)
})

onUnmounted(() => {
  window.removeEventListener('target-updated', fetchTargets)
})

async function fetchTargets() {
  isLoading.value = true
  try {
    const res = await targetsApi.getTargets()
    targets.value = res.data || []
    summary.value = res.summary || {}
  } catch (err) {
    console.error('Failed to fetch targets', err)
    targets.value = []
  } finally {
    isLoading.value = false
  }
}

function openTargetModal(target = null) {
  editingTarget.value = target
  if (target) {
    targetForm.value = { title: target.title, description: target.description, focus_dimension: target.focus_dimension, priority: target.priority, due_date: target.due_date || '', subtasks: [] }
  } else {
    targetForm.value = { title: '', description: '', focus_dimension: 'General', priority: 'medium', due_date: '', subtasks: [{ title: '' }] }
  }
  showTargetModal.value = true
}

async function saveTarget() {
  isSaving.value = true
  try {
    if (editingTarget.value) {
      await targetsApi.updateTarget(editingTarget.value.id, targetForm.value)
      showToast('Target updated!')
    } else {
      await targetsApi.createTarget(targetForm.value)
      showToast('Target created!')
    }
    showTargetModal.value = false
    await fetchTargets()
  } catch (err) {
    showToast('Failed to save target.', 'error')
  } finally {
    isSaving.value = false
  }
}

function confirmDeleteTarget(id) {
  targetToDelete.value = id
  showDeleteModal.value = true
}

async function executeDelete() {
  if (!targetToDelete.value) return
  const id = targetToDelete.value
  try {
    await targetsApi.deleteTarget(id)
    targets.value = targets.value.filter(t => t.id !== id)
    showToast('Target deleted.')
    await fetchTargets()
  } catch (err) {
    showToast('Failed to delete.', 'error')
  } finally {
    showDeleteModal.value = false
    targetToDelete.value = null
  }
}

async function toggleSubtask(targetId, subtaskId) {
  try {
    await targetsApi.toggleSubtask(targetId, subtaskId)
    await fetchTargets()
  } catch (err) {
    showToast('Failed to toggle subtask.', 'error')
  }
}

async function addSubtask(targetId) {
  const title = newSubtask[targetId]?.trim()
  if (!title) return
  try {
    await targetsApi.createSubtask(targetId, { title })
    newSubtask[targetId] = ''
    await fetchTargets()
    showToast('Subtask added!')
  } catch (err) {
    showToast('Failed to add subtask.', 'error')
  }
}

async function deleteSubtask(targetId, subtaskId) {
  try {
    await targetsApi.deleteSubtask(targetId, subtaskId)
    await fetchTargets()
  } catch (err) {
    showToast('Failed to delete subtask.', 'error')
  }
}

function showToast(message, type = 'success') {
  toast.value = { message, type }
  setTimeout(() => toast.value = null, 3000)
}

function priorityClass(p) {
  const map = { high: 'bg-rose-50 text-rose-500', medium: 'bg-amber-50 text-amber-500', low: 'bg-slate-50 text-slate-400' }
  return map[p] || 'bg-slate-50 text-slate-400'
}

function statusBadge(s) {
  const map = { completed: 'bg-emerald-50 text-emerald-500', in_progress: 'bg-blue-50 text-blue-500', not_started: 'bg-slate-50 text-slate-400', paused: 'bg-amber-50 text-amber-500' }
  return map[s] || 'bg-slate-50 text-slate-400'
}
</script>

// finpro-mobile-expo/src/app/(dashboard)/weekly-targets.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, ScrollView, TouchableOpacity, Modal, TextInput, Alert, ActivityIndicator } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { useColorScheme } from 'nativewind';
import { targetsApi } from '../../services/api';

const DIMENSIONS = ['General', 'Planning', 'Time Management', 'Cognitive Strategy', 'Reflection'];
const PRIORITIES = ['low', 'medium', 'high'];

export default function WeeklyTargetsScreen() {
  const { colorScheme } = useColorScheme();
  const [targets, setTargets] = useState<any[]>([]);
  const [summary, setSummary] = useState<any>({});
  const [isLoading, setIsLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [editingTarget, setEditingTarget] = useState<any>(null);
  const [newSubtaskText, setNewSubtaskText] = useState<Record<string, string>>({});

  // Form state
  const [form, setForm] = useState({
    title: '',
    description: '',
    focus_dimension: 'General',
    priority: 'medium',
    due_date: '',
    subtasks: [{ title: '' }],
  });

  // Dropdown visibility
  const [showDimDropdown, setShowDimDropdown] = useState(false);
  const [showPriorityDropdown, setShowPriorityDropdown] = useState(false);

  const fetchTargets = useCallback(async () => {
    setIsLoading(true);
    try {
      const res = await targetsApi.getTargets();
      setTargets(res.data || []);
      setSummary(res.summary || {});
    } catch (err) {
      console.error('Failed to fetch targets', err);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => { fetchTargets(); }, []);

  const openModal = (target: any = null) => {
    setEditingTarget(target);
    if (target) {
      setForm({
        title: target.title || '',
        description: target.description || '',
        focus_dimension: target.focus_dimension || 'General',
        priority: target.priority || 'medium',
        due_date: target.due_date || '',
        subtasks: [],
      });
    } else {
      setForm({
        title: '',
        description: '',
        focus_dimension: 'General',
        priority: 'medium',
        due_date: '',
        subtasks: [{ title: '' }],
      });
    }
    setShowDimDropdown(false);
    setShowPriorityDropdown(false);
    setShowModal(true);
  };

  const handleSave = async () => {
    if (!form.title.trim()) { Alert.alert('Error', 'Title is required'); return; }
    setIsSaving(true);
    try {
      const payload: any = {
        title: form.title,
        description: form.description,
        focus_dimension: form.focus_dimension,
        priority: form.priority,
        subtasks: form.subtasks.filter(s => s.title.trim()),
      };
      if (form.due_date) {
        payload.due_date = form.due_date;
      }
      if (editingTarget) {
        await targetsApi.updateTarget(editingTarget.id, payload);
      } else {
        await targetsApi.createTarget(payload);
      }
      setShowModal(false);
      await fetchTargets();
    } catch (err) {
      Alert.alert('Error', 'Failed to save target');
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = (id: string) => {
    Alert.alert('Delete Target', 'Are you sure? This will delete all subtasks too.', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Delete', style: 'destructive', onPress: async () => {
        try {
          await targetsApi.deleteTarget(id);
          await fetchTargets();
        } catch { Alert.alert('Error', 'Failed to delete'); }
      }},
    ]);
  };

  const handleToggleSubtask = async (targetId: string, subtaskId: string) => {
    try {
      await targetsApi.toggleSubtask(targetId, subtaskId);
      await fetchTargets();
    } catch { Alert.alert('Error', 'Failed to toggle subtask'); }
  };

  const handleAddSubtask = async (targetId: string) => {
    const title = newSubtaskText[targetId]?.trim();
    if (!title) return;
    try {
      await targetsApi.createSubtask(targetId, { title });
      setNewSubtaskText(prev => ({ ...prev, [targetId]: '' }));
      await fetchTargets();
    } catch { Alert.alert('Error', 'Failed to add subtask'); }
  };

  const handleDeleteSubtask = async (targetId: string, subtaskId: string) => {
    try {
      await targetsApi.deleteSubtask(targetId, subtaskId);
      await fetchTargets();
    } catch { Alert.alert('Error', 'Failed to delete subtask'); }
  };

  const addFormSubtask = () => {
    setForm(prev => ({ ...prev, subtasks: [...prev.subtasks, { title: '' }] }));
  };

  const removeFormSubtask = (index: number) => {
    setForm(prev => ({
      ...prev,
      subtasks: prev.subtasks.filter((_, i) => i !== index),
    }));
  };

  const updateFormSubtask = (index: number, value: string) => {
    setForm(prev => {
      const updated = [...prev.subtasks];
      updated[index] = { title: value };
      return { ...prev, subtasks: updated };
    });
  };

  const priorityClasses = (p: string) => {
    if (p === 'high') return { bg: 'bg-rose-50 dark:bg-rose-500/10', text: 'text-rose-500 dark:text-rose-400' };
    if (p === 'medium') return { bg: 'bg-amber-50 dark:bg-amber-500/10', text: 'text-amber-500 dark:text-amber-400' };
    return { bg: 'bg-slate-50 dark:bg-slate-500/10', text: 'text-slate-400 dark:text-slate-400' };
  };

  const statusClasses = (s: string) => {
    if (s === 'completed') return { bg: 'bg-emerald-50 dark:bg-emerald-500/10', text: 'text-emerald-500 dark:text-emerald-400' };
    if (s === 'in_progress') return { bg: 'bg-blue-50 dark:bg-blue-500/10', text: 'text-blue-500 dark:text-blue-400' };
    return { bg: 'bg-slate-50 dark:bg-slate-500/10', text: 'text-slate-400 dark:text-slate-400' };
  };

  return (
    <View className="flex-1 bg-surface-warm dark:bg-dark-bg">
      <StatusBar style={colorScheme === "dark" ? "light" : "dark"} />
      <ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 32 }}>

        {/* Header */}
        <View className="px-6 pt-16 pb-6 border-b border-navy-100 dark:border-dark-border">
          <View className="flex-row items-center justify-between mb-2">
            <Text className="text-2xl font-black text-navy-900 dark:text-text-primary">Weekly Targets</Text>
            <TouchableOpacity onPress={() => openModal()} className="bg-orange-500 py-2 px-4 rounded-full">
              <Text className="text-white font-bold text-xs">+ Add Target</Text>
            </TouchableOpacity>
          </View>
          <Text className="text-navy-500 dark:text-text-muted text-xs">Set measurable goals and track completion.</Text>
        </View>

        {/* Dashboard Cards */}
        <View className="px-6 py-6" style={{ gap: 12 }}>
          <View className="flex-row" style={{ gap: 12 }}>
            <View className="flex-1 bg-navy-900 dark:bg-dark-panel p-4 rounded-2xl">
              <Text className="text-[9px] font-black text-navy-300 uppercase tracking-widest mb-1">Total Targets</Text>
              <Text className="text-white text-2xl font-black">{targets.length}</Text>
            </View>
            <View className="flex-1 bg-navy-900 dark:bg-dark-panel p-4 rounded-2xl">
              <Text className="text-[9px] font-black text-emerald-300 uppercase tracking-widest mb-1">Completed</Text>
              <Text className="text-emerald-400 text-2xl font-black">{targets.filter((t: any) => t.status === 'completed').length}</Text>
            </View>
          </View>
          <View className="flex-row" style={{ gap: 12 }}>
            <View className="flex-1 bg-navy-900 dark:bg-dark-panel p-4 rounded-2xl">
              <Text className="text-[9px] font-black text-brand-300 uppercase tracking-widest mb-1">Completion Rate</Text>
              <Text className="text-brand-400 text-2xl font-black">
                {targets.length > 0 ? Math.round((targets.filter((t: any) => t.status === 'completed').length / targets.length) * 100) : 0}%
              </Text>
            </View>
            <View className="flex-1 bg-navy-900 dark:bg-dark-panel p-4 rounded-2xl">
              <Text className="text-[9px] font-black text-navy-300 uppercase tracking-widest mb-1">Primary Focus</Text>
              <Text className="text-white text-sm font-bold mt-1">
                {targets.length > 0 ? targets[0].focus_dimension || 'General' : 'No focus yet'}
              </Text>
            </View>
          </View>
        </View>

        {/* Target List */}
        {isLoading ? (
          <ActivityIndicator size="large" color="#F97316" style={{ marginTop: 40 }} />
        ) : targets.length === 0 ? (
          <View className="px-6 py-10 items-center">
            <Text className="text-navy-300 font-bold">No targets found.</Text>
          </View>
        ) : (
          <View className="px-6" style={{ gap: 16 }}>
            {targets.map((target: any) => {
              const pc = priorityClasses(target.priority);
              const sc = statusClasses(target.status);
              return (
                <View key={target.id} className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border p-5 rounded-3xl shadow-sm">
                  {/* Badges */}
                  <View className="flex-row flex-wrap mb-2" style={{ gap: 6 }}>
                    <View className={`${pc.bg} px-2 py-1 rounded-md`}>
                      <Text className={`${pc.text} text-[9px] font-black uppercase tracking-widest`}>{target.priority}</Text>
                    </View>
                    <View className="bg-brand-50 dark:bg-brand-500/10 px-2 py-1 rounded-md">
                      <Text className="text-brand-500 text-[9px] font-black uppercase tracking-widest">{target.focus_dimension}</Text>
                    </View>
                    <View className={`${sc.bg} px-2 py-1 rounded-md`}>
                      <Text className={`${sc.text} text-[9px] font-black uppercase tracking-widest`}>{target.status?.replace('_', ' ')}</Text>
                    </View>
                  </View>

                  {/* Title & Description */}
                  <Text className="text-navy-900 dark:text-text-primary text-lg font-black mb-1">{target.title}</Text>
                  {target.description ? <Text className="text-navy-500 dark:text-text-muted text-xs font-medium mb-1">{target.description}</Text> : null}
                  {target.due_date ? <Text className="text-navy-300 dark:text-text-secondary text-[10px] font-bold mb-3">Due: {target.due_date}</Text> : null}

                  {/* Progress Bar */}
                  <View className="mb-3">
                    <View className="flex-row items-center justify-between mb-1">
                      <Text className="text-navy-500 dark:text-text-muted text-[9px] font-black uppercase tracking-widest">Progress</Text>
                      <Text className="text-navy-900 dark:text-text-primary text-xs font-black">{target.progress || 0}%</Text>
                    </View>
                    <View className="w-full h-2 bg-navy-50 dark:bg-dark-surface rounded-full overflow-hidden">
                      <View
                        className="h-full rounded-full"
                        style={{
                          width: `${target.progress || 0}%`,
                          backgroundColor: (target.progress || 0) >= 100 ? '#10B981' : '#F97316',
                        }}
                      />
                    </View>
                  </View>

                  {/* Subtasks */}
                  {target.subtasks?.map((sub: any) => (
                    <View key={sub.id} className="flex-row items-center py-2 border-b border-[#F0F4F8]" style={{ gap: 10 }}>
                      <TouchableOpacity
                        onPress={() => handleToggleSubtask(target.id, sub.id)}
                        style={{
                          width: 20, height: 20, borderRadius: 5, borderWidth: 2,
                          borderColor: sub.is_completed ? '#10B981' : 'rgba(156,163,175,0.3)',
                          backgroundColor: sub.is_completed ? '#10B981' : 'transparent',
                          alignItems: 'center', justifyContent: 'center',
                        }}
                      >
                        {sub.is_completed && <Text style={{ color: '#fff', fontSize: 10, fontWeight: '900' }}>✓</Text>}
                      </TouchableOpacity>
                      <Text className={`flex-1 text-sm font-bold ${sub.is_completed ? 'text-navy-300 dark:text-text-secondary line-through' : 'text-navy-900 dark:text-text-primary'}`}>{sub.title}</Text>
                      <TouchableOpacity onPress={() => handleDeleteSubtask(target.id, sub.id)}>
                        <Text style={{ color: '#9FB3C8', fontSize: 16, fontWeight: '700' }}>×</Text>
                      </TouchableOpacity>
                    </View>
                  ))}

                  {/* Add Subtask Inline */}
                  <View className="flex-row items-center mt-2" style={{ gap: 8 }}>
                    <TextInput
                      value={newSubtaskText[target.id] || ''}
                      onChangeText={t => setNewSubtaskText(prev => ({ ...prev, [target.id]: t }))}
                      placeholder="Add subtask..."
                      placeholderTextColor="#9FB3C8"
                      onSubmitEditing={() => handleAddSubtask(target.id)}
                      className="flex-1 text-sm font-bold text-navy-900 dark:text-text-primary border-b border-dashed border-navy-100 dark:border-dark-border py-1"
                    />
                    {(newSubtaskText[target.id] || '').trim() ? (
                      <TouchableOpacity onPress={() => handleAddSubtask(target.id)}>
                        <Text className="text-brand-500 text-xs font-black">Add</Text>
                      </TouchableOpacity>
                    ) : null}
                  </View>

                  {/* Action Buttons */}
                  <View className="flex-row mt-4 pt-3 border-t border-[#F0F4F8]" style={{ gap: 8 }}>
                    <TouchableOpacity
                      onPress={() => openModal(target)}
                      className="flex-1 bg-navy-50 dark:bg-dark-surface py-2 rounded-xl items-center"
                    >
                      <Text className="text-navy-600 dark:text-text-primary text-xs font-bold">Edit</Text>
                    </TouchableOpacity>
                    <TouchableOpacity
                      onPress={() => handleDelete(target.id)}
                      className="flex-1 bg-rose-50 dark:bg-rose-500/10 py-2 rounded-xl items-center"
                    >
                      <Text className="text-rose-500 dark:text-rose-400 text-xs font-bold">Delete</Text>
                    </TouchableOpacity>
                  </View>
                </View>
              );
            })}
          </View>
        )}
      </ScrollView>

      {/* Add/Edit Modal */}
      <Modal visible={showModal} transparent animationType="fade">
        <View style={{ flex: 1, backgroundColor: 'rgba(11,17,32,0.5)', justifyContent: 'center', padding: 20 }}>
          <View className="bg-white dark:bg-dark-panel rounded-3xl p-6" style={{ maxHeight: '85%' }}>
            <ScrollView showsVerticalScrollIndicator={false}>
              <Text className="text-xl font-black text-navy-900 dark:text-text-primary mb-5">
                {editingTarget ? 'Edit Target' : 'Add Weekly Target'}
              </Text>

              {/* Title */}
              <Text className="text-[9px] font-black text-navy-500 dark:text-text-muted uppercase tracking-widest mb-1">Title *</Text>
              <TextInput
                value={form.title}
                onChangeText={t => setForm(p => ({ ...p, title: t }))}
                placeholder="e.g. Complete Chapter 5"
                placeholderTextColor="#9FB3C8"
                className="bg-surface-warm dark:bg-dark-bg border border-navy-100 dark:border-dark-border rounded-xl py-3 px-4 text-sm font-bold text-navy-900 dark:text-text-primary mb-4"
              />

              {/* Description */}
              <Text className="text-[9px] font-black text-navy-500 dark:text-text-muted uppercase tracking-widest mb-1">Description</Text>
              <TextInput
                value={form.description}
                onChangeText={t => setForm(p => ({ ...p, description: t }))}
                multiline
                numberOfLines={2}
                className="bg-surface-warm dark:bg-dark-bg border border-navy-100 dark:border-dark-border rounded-xl py-3 px-4 text-sm font-bold text-navy-900 dark:text-text-primary mb-4"
                style={{ minHeight: 60, textAlignVertical: 'top' }}
              />

              {/* Focus Dimension & Priority Row */}
              <View className="flex-row mb-4" style={{ gap: 12 }}>
                {/* Focus Dimension */}
                <View style={{ flex: 1 }}>
                  <Text className="text-[9px] font-black text-navy-500 dark:text-text-muted uppercase tracking-widest mb-1">Focus Dimension</Text>
                  <TouchableOpacity
                    onPress={() => { setShowDimDropdown(!showDimDropdown); setShowPriorityDropdown(false); }}
                    className="bg-surface-warm dark:bg-dark-bg border border-navy-100 dark:border-dark-border rounded-xl py-3 px-4 flex-row items-center justify-between"
                  >
                    <Text className="text-sm font-bold text-navy-900 dark:text-text-primary">{form.focus_dimension}</Text>
                    <Text className="text-navy-500 dark:text-text-muted">▼</Text>
                  </TouchableOpacity>
                  {showDimDropdown && (
                    <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border rounded-xl mt-1 shadow-sm" style={{ position: 'absolute', top: 62, left: 0, right: 0, zIndex: 100 }}>
                      {DIMENSIONS.map(d => (
                        <TouchableOpacity
                          key={d}
                          onPress={() => { setForm(p => ({ ...p, focus_dimension: d })); setShowDimDropdown(false); }}
                          style={{ padding: 10, backgroundColor: form.focus_dimension === d ? '#F97316' : 'transparent', borderRadius: 8, margin: 2 }}
                        >
                          <Text className={`text-[13px] font-bold ${form.focus_dimension === d ? 'text-white' : 'text-navy-900 dark:text-text-primary'}`}>{d}</Text>
                        </TouchableOpacity>
                      ))}
                    </View>
                  )}
                </View>
                {/* Priority */}
                <View style={{ flex: 1 }}>
                  <Text className="text-[9px] font-black text-navy-500 dark:text-text-muted uppercase tracking-widest mb-1">Priority</Text>
                  <TouchableOpacity
                    onPress={() => { setShowPriorityDropdown(!showPriorityDropdown); setShowDimDropdown(false); }}
                    className="bg-surface-warm dark:bg-dark-bg border border-navy-100 dark:border-dark-border rounded-xl py-3 px-4 flex-row items-center justify-between"
                  >
                    <Text className="text-sm font-bold text-navy-900 dark:text-text-primary capitalize">{form.priority}</Text>
                    <Text className="text-navy-500 dark:text-text-muted">▼</Text>
                  </TouchableOpacity>
                  {showPriorityDropdown && (
                    <View className="bg-white dark:bg-dark-panel border border-navy-100 dark:border-dark-border rounded-xl mt-1 shadow-sm" style={{ position: 'absolute', top: 62, left: 0, right: 0, zIndex: 100 }}>
                      {PRIORITIES.map(p => (
                        <TouchableOpacity
                          key={p}
                          onPress={() => { setForm(prev => ({ ...prev, priority: p })); setShowPriorityDropdown(false); }}
                          style={{ padding: 10, backgroundColor: form.priority === p ? '#F97316' : 'transparent', borderRadius: 8, margin: 2 }}
                        >
                          <Text className={`text-[13px] font-bold capitalize ${form.priority === p ? 'text-white' : 'text-navy-900 dark:text-text-primary'}`}>{p}</Text>
                        </TouchableOpacity>
                      ))}
                    </View>
                  )}
                </View>
              </View>

              {/* Due Date */}
              <Text className="text-[9px] font-black text-navy-500 dark:text-text-muted uppercase tracking-widest mb-1">Due Date</Text>
              <TextInput
                value={form.due_date}
                onChangeText={t => setForm(p => ({ ...p, due_date: t }))}
                placeholder="YYYY-MM-DD"
                placeholderTextColor="#9FB3C8"
                className="bg-surface-warm dark:bg-dark-bg border border-navy-100 dark:border-dark-border rounded-xl py-3 px-4 text-sm font-bold text-navy-900 dark:text-text-primary mb-4"
              />

              {/* Initial Subtasks (create mode only) */}
              {!editingTarget && (
                <View className="mb-4">
                  <Text className="text-[9px] font-black text-navy-500 dark:text-text-muted uppercase tracking-widest mb-2">Initial Subtasks</Text>
                  {form.subtasks.map((st, i) => (
                    <View key={i} className="flex-row items-center mb-2" style={{ gap: 8 }}>
                      <TextInput
                        value={st.title}
                        onChangeText={t => updateFormSubtask(i, t)}
                        placeholder={`Subtask ${i + 1}`}
                        placeholderTextColor="#9FB3C8"
                        className="flex-1 bg-surface-warm dark:bg-dark-bg border border-navy-100 dark:border-dark-border rounded-xl py-2 px-4 text-sm font-bold text-navy-900 dark:text-text-primary"
                      />
                      <TouchableOpacity onPress={() => removeFormSubtask(i)}>
                        <Text style={{ color: '#9FB3C8', fontSize: 18, fontWeight: '700' }}>×</Text>
                      </TouchableOpacity>
                    </View>
                  ))}
                  <TouchableOpacity onPress={addFormSubtask}>
                    <Text className="text-brand-500 text-sm font-bold">+ Add subtask</Text>
                  </TouchableOpacity>
                </View>
              )}

              {/* Buttons */}
              <View className="flex-row mt-2" style={{ gap: 12 }}>
                <TouchableOpacity
                  onPress={() => setShowModal(false)}
                  className="flex-1 bg-navy-50 dark:bg-dark-surface py-3 rounded-xl items-center"
                >
                  <Text className="text-navy-600 dark:text-text-primary font-bold">Cancel</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  onPress={handleSave}
                  disabled={isSaving}
                  className="flex-1 bg-brand-500 py-3 rounded-xl items-center"
                  style={{ opacity: isSaving ? 0.5 : 1 }}
                >
                  <Text className="text-white font-bold">{isSaving ? 'Saving...' : editingTarget ? 'Update' : 'Create'}</Text>
                </TouchableOpacity>
              </View>
            </ScrollView>
          </View>
        </View>
      </Modal>
    </View>
  );
}
